"""init schema

Revision ID: 14b84f94b915
Revises:
Create Date: 2026-09-24 12:45:26.451973

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14b84f94b915"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("target", sa.String(length=120), nullable=False),
        sa.Column("args", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("applicant", sa.String(length=64), nullable=False),
        sa.Column("approver", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_action"), "approvals", ["action"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_index(op.f("ix_approvals_tenant"), "approvals", ["tenant"], unique=False)
    op.create_table(
        "run_steps",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("args", sa.Text(), nullable=False),
        sa.Column("result_digest", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("planner_source", sa.String(length=8), nullable=False),
        sa.Column("approval_id", sa.String(length=32), nullable=False),
        sa.Column("trace_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_steps_planner_source"), "run_steps", ["planner_source"], unique=False
    )
    op.create_index(op.f("ix_run_steps_run_id"), "run_steps", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_steps_status"), "run_steps", ["status"], unique=False)
    op.create_index(op.f("ix_run_steps_tenant"), "run_steps", ["tenant"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("checkpoint", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_tenant"), "tasks", ["tenant"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("trace_id", sa.String(length=40), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("args", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_calls_name"), "tool_calls", ["name"], unique=False)
    op.create_index(op.f("ix_tool_calls_tenant"), "tool_calls", ["tenant"], unique=False)
    op.create_index(op.f("ix_tool_calls_trace_id"), "tool_calls", ["trace_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("pwd_hash", sa.String(length=256), nullable=False),
        sa.Column("roles", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "username", name="uq_users_tenant_username"),
    )
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tool_calls_trace_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_tenant"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_name"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_tasks_tenant"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_run_steps_tenant"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_status"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_run_id"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_planner_source"), table_name="run_steps")
    op.drop_table("run_steps")
    op.drop_index(op.f("ix_approvals_tenant"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
