"""add data_assets（数据资产目录落库位）

Revision ID: 404ff16a2d44
Revises: 93975c6df6e7
Create Date: 2026-09-27 00:14:30.675821

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "404ff16a2d44"
down_revision: str | Sequence[str] | None = "93975c6df6e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_assets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("asset_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant", "category", "asset_name", name="uq_data_assets_tenant_category_name"
        ),
    )
    op.create_index(op.f("ix_data_assets_tenant"), "data_assets", ["tenant"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_assets_tenant"), table_name="data_assets")
    op.drop_table("data_assets")
    # ### end Alembic commands ###
