"""add notifications table

Revision ID: 4710c1599916
Revises: 14b84f94b915
Create Date: 2026-09-24 15:59:31.978702

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4710c1599916"
down_revision: str | Sequence[str] | None = "14b84f94b915"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ref_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "username", "kind", "ref_id", name="uq_notify_dedupe"),
    )
    op.create_index(op.f("ix_notifications_kind"), "notifications", ["kind"], unique=False)
    op.create_index(op.f("ix_notifications_ref_id"), "notifications", ["ref_id"], unique=False)
    op.create_index(op.f("ix_notifications_tenant"), "notifications", ["tenant"], unique=False)
    op.create_index(op.f("ix_notifications_username"), "notifications", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_username"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_tenant"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_ref_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_kind"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
