"""add scheduled_jobs

Revision ID: 93975c6df6e7
Revises: 46bf9fe408ba
Create Date: 2026-09-25 12:55:05.824628

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93975c6df6e7"
down_revision: str | Sequence[str] | None = "46bf9fe408ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("schedule", sa.Text(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_result", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_jobs_job_type"), "scheduled_jobs", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_jobs_next_run_at"), "scheduled_jobs", ["next_run_at"], unique=False
    )
    op.create_index(op.f("ix_scheduled_jobs_tenant"), "scheduled_jobs", ["tenant"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_jobs_tenant"), table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_next_run_at"), table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_job_type"), table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    # ### end Alembic commands ###
